import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyFullArticle, emptyQuickBrief, toPublishedPost, validateArticle } from '../src/lib/article-contract';

test('rejects malformed and duplicated article representations',()=>{
  const quick={...emptyQuickBrief(),category:'Tech',headline:'A real headline here',quick_summary:'same summary words repeated enough to look acceptable but still deliberately identical across both article representations for this contract check',three_things_to_know:['One substantive fact here','Second substantive fact here','Third substantive fact here']};
  const full={...emptyFullArticle(),headline:'A longer real headline',hook:'A useful hook with enough words to pass the minimum validation rule.',in_20_seconds:quick.quick_summary,what_happened:quick.quick_summary,why_this_matters:'This development matters because it changes the market for customers, competitors, workers and investors across the wider sector over the coming years.',takeaways:['First useful takeaway here','Second useful takeaway here','Third useful takeaway here']};
  const issues=validateArticle({quick_brief:quick,full_article:full});
  assert(issues.some(i=>i.path==='content'));
  assert(issues.some(i=>i.path==='full_article.explore_sections'));
});

test('publisher emits one mobile-compatible schema-v2 post',()=>{
  const article:any={id:'x',schema_version:2,status:'draft',title:'',category:'Article',quick_brief:{category:'Tech',headline:'New product reaches Indian market',quick_summary:'A detailed summary with enough reporting context to explain who did what, when it happened, where it occurred and what changes next for the people affected by the announcement.',three_things_to_know:['Company launched the product nationwide','Customers receive access beginning today','Pricing remains below its closest rival'],key_number:{value:'₹99','label':'Entry price'}},full_article:{headline:'New product reaches the Indian market with a lower entry price',hook:'A lower price brings a previously premium product within reach of more Indian customers.',in_20_seconds:'A concise full-story orientation.',what_happened:'The company launched its new product across India after a six-month pilot in three cities. The release adds two configurations, nationwide support and a lower entry price, while existing customers retain their current plans and service terms without changes.',why_this_matters:'Lower pricing can expand the addressable market and pressure established competitors to respond. Customers gain another option, while suppliers and distributors may see higher volumes if adoption grows beyond the initial urban launch markets.',bigger_picture:'The launch fits a broader move toward lower-cost products designed around Indian purchasing patterns and service constraints, rather than importing premium global configurations without adaptation.',key_stats:[],explore_sections:[{title:'Product details',summary:'What ships',content:'The product includes a redesigned entry configuration, nationwide support coverage and a service plan tailored to customers outside major cities. Distribution begins through existing retail and online channels this month.',items:[]},{title:'Market impact',summary:'Who responds',content:'Competitors now face a lower reference price in an already crowded category. Retail partners expect the accessible configuration to attract first-time buyers who previously delayed a purchase.',items:[]}],takeaways:['The product launches nationwide this month','A lower entry price broadens customer access','Existing customers keep their current terms'],quote:null},isFeatured:true};
  const post=toPublishedPost(article,{uid:'u',name:'Editor',email:'e@example.com'});
  assert.equal(post.schema_version,2);assert.equal(post.category,'Article');assert.equal(post.status,'approved');assert(post.quick_brief);assert(post.full_article);assert(!('fullArticle' in post));
});
